---
title: "27_10_2020"
author: "Caroline Busse"
date: "27 Oktober 2020"
output: html_document
---

```{r data check}
# install.packages("RCurl")
library(RCurl)
library(tidyverse)

df <- read_csv("https://raw.githubusercontent.com/wegmann/R_data/master/Steigerwald_sample_points_all_data_subset_withNames.csv")

# consistency check
head(df)
summary(df)
tail(df)
plot(df$L8.ndvi, df$L8.evi)
str(df)
names(df)
dim(df)
class(df)

```
```{r indexing}
x <- seq(1,100,by=2.5)

x[5]

x[4:10]

# all but second position
x[-2]

idx <- c(1,4,6)
x[idx]
x[-idx]

# querying
x > 20
x[x<10 | x > 30]

# change values
x2 <- numeric(length(x))
x2[x<=30] <- 1
x2[(x>30) & (x<70)] <-2
x2[x>70] <- 3

```


```{r Matrix}

m1 <- matrix(c(4,7,3,8,9,2), nrow = 2)
m1

m2 <- matrix(
  c(2,4,3,1,5,7),
  nrow = 2,
  ncol = 3,
  byrow = TRUE
)
m2

m1[,2]
m1[2,]
m1[2,2]

# create matrix out of vector
# create vector with 80 entries based on normal distribution
numbers_1 <- rnorm(80,mean=0,sd=1)
mat_1 <- matrix(numbers_1,nrow=20,ncol=4)
mat_1

df_1 <- data.frame(mat_1)
names(df_1) <- c("var1", "var2", "var3", "var4")

head(df_1)
summary(df_1)

```

```{r data frame}

test <- data.frame(A=c(1,2,3),B=c("aB1","aB2","aB3"))

test[,1]
test[,"A"]
test$A

# rep(LETTERS,100)[1:100] would repeat alphabet 100 times, we then cut it to 100 values
df_1 <- data.frame(plot="location_name_1", measure1=runif(100)*1000,measure2=round(runif(100)*100),value=rnorm(100,2,1),ID=rep(LETTERS,100)[1:100])

df_2 <- data.frame(plot="location_name_2", measure1=runif(50)*100,measure2=round(runif(50)*10),value=rnorm(50),ID=rep(LETTERS,50)[1:50])

df <- rbind(df_1,df_2)
head(df)

df[,c('plot','measure1','measure2')]
df[66:70,c('plot','measure1','measure2')]


```

```{r List}
a <- runif(199)
b <- c("aa", "bb", "cc", "dd", "ee")
c <- list(a,b)
c

c[2]
#outputs original data type
c[[2]]
c[[2]][1]

a <- list(obj_1=runif(100),obj_2=c("aa","bb"),obj_3=c(1,2,4))
a$obj_1
a[["obj_1"]]
a[[1]]

a <- list(m1=matrix(runif(50),nrow=5),v1=c(1,6,10),df1=data.frame(a=runif(100),b=rnorm(100)))
a$df1[,1]

```

```{r task}
plot(df$measure1,df$measure2)

plot(df$measure1[10:20])

install.packages("scatterplot3d")
library(scatterplot3d)

attach(df)

scatterplot3d(measure1,measure2,value)

coplot(measure1 ~ measure2 | value)
```

