---
title: "day5_live"
author: "Caroline Busse"
date: "27 11 2020"
output: html_document
---

```{r}
library(sf)
library(ggplot2)

df_aggr <- read.csv("data/day4_data_energy_prod_EU_2020-08-03_2020-08-09_ctr_code_aggr_ctr.csv")
ctr <- st_read("data/ne_10m_admin_0_countries/ne_10m_admin_0_countries_ctr_code.gpkg")
```


```{r}
# join both
ctr_df <- merge(ctr, df_aggr, by = "ctr_code")
# export joined dataset, if you want: st_write(ctr_df, "path/to/your_new_file.gpkg)
ggplot(ctr_df) + geom_sf()

# crop to European mainland
box <- st_bbox(c(xmin = -30, ymin = 35, xmax = 33, ymax = 81), crs = st_crs(ctr_df))
ctr_df_eur <- st_crop(ctr_df, box)
ggplot(ctr_df_eur) + geom_sf()

# Reproject/transform unprojected LatLon (WGS84) to LAEA (ETRS89)
ctr_df_eur_laea <- st_transform(ctr_df_eur, st_crs(3035))
ggplot(ctr_df_eur_laea) + geom_sf()

# plot production output
ggplot() + geom_sf(data = ctr_df_eur_laea, aes(colour = ActualGenerationOutput), alpha = 0.6) +
  scale_colour_gradientn(colours = viridis::inferno(8))
```

