---
title: "tasks_03_11_2020_Energy Production"
author: "Caroline Busse"
date: "3 11 2020"
output: html_document
---

```{r basic data cleaning}
library(dplyr)
library(data.table)
energy <- read.csv("data/day2_data_energy_prod_EU_2020-08-03_2020-08-09.csv", fileEncoding = "UTF-8")

summary(energy)
glimpse(energy)

# convert data types ----
energy_new <- energy %>%
  mutate(Month = as.factor(Month))

energy_new <- energy_new %>%
  mutate(Day = as.factor(Day))

energy_new <- energy_new %>%
  mutate(DateTime = as.POSIXct(DateTime))

energy_new <- energy_new %>%
  mutate(DayofWeek = as.factor(weekdays(DateTime)))

energy_new <- energy_new %>%
  mutate(Time = as.ITime(DateTime))

unique(energy_new$ResolutionCode)
energy_new <- energy_new %>%
  mutate(ResolutionCode = as.factor(ResolutionCode))

sort(unique(energy_new$AreaCode))
unique(energy_new$AreaTypeCode)
energy_new <- energy_new %>%
  mutate(AreaTypeCode = as.factor(AreaTypeCode))

# group german mapcodes to "DE"
energy_new$CountryCode <- energy_new$MapCode
energy_new$CountryCode[grep("DE_", energy_new$CountryCode)] <- "DE"

unique(energy_new$CountryCode)
energy_new <- energy_new %>%
  mutate(CountryCode = as.factor(CountryCode))
levels(energy_new$CountryCode)

sort(unique(energy_new$ProductionTypeName))
# group production types
energy_new$ProductionGroup <- energy_new$ProductionTypeName
energy_new$ProductionGroup[grep("Fossil", energy_new$ProductionGroup)] <- "Fossil"
energy_new$ProductionGroup[grep("Hydro", energy_new$ProductionGroup)] <- "Hydro"
energy_new$ProductionGroup[grep("Wind", energy_new$ProductionGroup)] <- "Wind"
sort(unique(energy_new$ProductionGroup))

energy_new <- energy_new %>%
  mutate(ProductionGroup = as.factor(ProductionGroup))
levels(energy_new$ProductionGroup )

energy_new <- energy_new %>%
  mutate(ProductionTypeName = as.factor(ProductionTypeName))

glimpse(energy_new)
summary(energy_new)

# attach df to search path
attach(energy_new)

# duplicates ----
# check for (full) duplicates
sum(duplicated(energy_new))

# check for partial duplicates
duplicates <- energy_new %>% 
  # same output as group_by() followed by summarize()
  count(PowerSystemResourceName,ProductionTypeName,DateTime) %>%
    filter(n>1)

```

```{r advanced data cleaning}

# check uniformity ----

# updatetime should be later than datetime
energy_new[which(UpdateTime < DateTime),]

# check outliers in energy production
plot(X, pch=1) # no outliers

# actual vs installed capacity (actual shouldn't be higher than installed capacity)
plot(energy_new$InstalledGenCapacity,energy_new$ActualGenerationOutput)

# outliers ----
outlier <- energy_new[which.max(energy_new$ActualGenerationOutput),]
energy_clean <- energy_new[-which.max(energy_new$ActualGenerationOutput),]
plot(energy_clean$InstalledGenCapacity,energy_clean$ActualGenerationOutput)

# second outlier
outlier <- energy_clean[which.max(energy_clean$ActualGenerationOutput),]
energy_clean <- energy_clean[-which.max(energy_clean$ActualGenerationOutput),]
plot(energy_clean$InstalledGenCapacity,energy_clean$ActualGenerationOutput)
# installedgencapacity limits ouput & some plant outputs exceed their capacity
# the higher the capacity the higher the output

# missing data ----
# install.packages("visdat")
library(visdat)

# visualize missing values
vis_miss(energy_clean, warn_large_data = F)
# only ActualGenerationOutput & ActualConsumption have NAs

sum(is.na(energy_clean$ActualGenerationOutput)) #8597
sum(is.na(energy_clean$ActualConsumption)) #261430

ago_nas <- energy_clean %>% filter(is.na(ActualGenerationOutput)) 
ac_nas <- energy_clean %>% filter(is.na(ActualConsumption))
      
energy_clean %>%
  arrange(X) %>%
    vis_miss(warn_large_data = F)

energy_clean %>%
  arrange(Day) %>%
    vis_miss(warn_large_data = F)

energy_clean %>%
  arrange(InstalledGenCapacity) %>%
    vis_miss(warn_large_data = F)

# no relation 

energy_clean$exc <- 0
energy_clean[which(energy_clean$ActualGenerationOutput > energy_clean$InstalledGenCapacity),22] <- 1

energy_clean$exceed <- as.factor(energy_clean$exc)
```


```{r visualizations, include=FALSE}
library(ggplot2)

# scatter plot ----
# aesthetics = scales onto which we map our data, geometries = visual elements used for our data 
# hallow circle shape = 1 to help with over-plotting
e1 <- energy_clean %>%
  filter(!is.na(ActualGenerationOutput)) %>%
  ggplot(aes(x = InstalledGenCapacity, y = ActualGenerationOutput, color = factor(exceed))) + 
    geom_point(shape = 1, alpha = 0.2) + 
    labs(color = "Output exceeds capacity") +
    ggtitle("Energy Output Exceeding Capacity")
# output often exceeds capacity, especially for lower to medium capacities


library(forcats)

# Distribution of Energy Production by Country & Production Group
e2 <- energy_clean %>%
  filter(!is.na(ActualGenerationOutput)) %>%
  # for several values per factor level, specify ordering function (to apply to determine the order)mean = default)
    mutate(CountryCode = fct_reorder(CountryCode, ActualGenerationOutput, .fun = 'max')) %>%
  ggplot(aes(ActualGenerationOutput, CountryCode, color = ProductionGroup)) +
    geom_point(position = "jitter") +
    labs(color = "Production group") +
    labs(title = "Energy Production Occurences by Country & Production Group 2020")
# DK uses mainly wind, CH mainly Hydro, NL mainly Fossil etc., France outputs most production occurrences 

# sum of energy production per country & facet grid per production group
e3 <- energy_clean %>%
  filter(!is.na(ActualGenerationOutput)) %>%
  ggplot(aes(ActualGenerationOutput, CountryCode, color = ActualGenerationOutput)) + 
    geom_point(position = "jitter", shape = 1, alpha = 0.2) +
    labs(title = "Energy Production per Country & Production Group 2020", color = "Energy output") +
    scale_color_continuous(high = "#132B43", low = "#56B1F7") +
    facet_grid(~ProductionGroup) +
    theme(axis.title.x=element_blank())
# most energy production based on fossil (only Switzerland not), least on geothermal (only Italy) & waste (only Germany)

# histogram ----
# avoid spaces between bars, set axis labels between bars (as continuous data)
ggplot(energy_clean, aes(ActualGenerationOutput, fill = DayofWeek)) + geom_histogram(binwidth = 60, center = 30) # many entries with low output
ggplot(energy_clean, aes(ActualGenerationOutput, fill = DayofWeek)) + geom_histogram(binwidth = 60, center = 30, position = "fill") # lowest energy production on sundays

ggplot(energy_clean, aes(ActualGenerationOutput, fill = exceed)) + geom_histogram(position = "fill") # no pattern


# bar plot ----
# order countries by production
e4 <- energy_clean %>%
  filter(!is.na(ActualGenerationOutput)) %>%
  group_by(CountryCode) %>%
  summarize(sumOutput = sum(ActualGenerationOutput)) %>%
  arrange(sumOutput) %>% 
  mutate(CountryCode = fct_reorder(CountryCode, sumOutput)) %>%
  ggplot(aes(CountryCode, sumOutput, fill = sumOutput)) + 
    geom_bar(stat="identity") +
    coord_flip() +
    scale_fill_continuous(high = "#132B43", low = "#56B1F7") +
    labs(title = "Energy Production by Country 2020", fill = "Sum of \nEnergy Production") +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank()) +
    geom_hline(yintercept = mean(aggregate(energy_clean$ActualGenerationOutput, list(energy_clean$CountryCode), sum)[[2]], na.rm = T), color="blue") 
# GB has highest energy production, ME lowest
#### add Production Group to graph ####

ggplot(energy_clean, aes(DayofWeek, fill = exceed)) + geom_bar()
ggplot(energy_clean, aes(DayofWeek, fill = exceed)) + geom_bar(position = "fill") # no clear pattern

energy_clean %>% 
  ggplot(aes(ProductionTypeName, fill = exceed)) + 
    geom_bar(position = "fill") +  
    coord_flip() # For Biomass, Hydro Run-of-river and poundage & Nuclear output most often exceeds capacity

# countries with most exceedings
energy_clean %>% 
  group_by(CountryCode, ProductionGroup) %>%
  summarize(countExceed = sum(exc)) %>%
  arrange(desc(countExceed)) %>%
  mutate(CountryCode = fct_reorder(CountryCode, countExceed)) %>%
  ggplot(aes(CountryCode, countExceed, fill = ProductionGroup)) +
    geom_bar(stat = "identity") +  
    coord_flip() +
    labs(title = "Capacity Exceedings per Country 2020", fill = "production group")
#### how add production group + sorting? ####

# graph where only top 10 production sites with highest exceedings (+ production type) are shown
energy_clean %>% 
  group_by(PowerSystemResourceName, ProductionGroup) %>%
  summarize(countExceed = sum(exc)) %>%
  arrange(desc(countExceed)) %>%
  mutate(PowerSystemResourceName = fct_reorder(PowerSystemResourceName, countExceed)) %>%
  head(10) %>%
  ggplot(aes(CountryCode, countExceed, fill = ProductionGroup)) +
    geom_bar(stat = "identity") +  
    coord_flip() +
    labs(title = "Capacity Exceedings per Power Plant 2020", fill = "production group")
    

# false indication, as temporal factor (e.g. some power plant reports more often)
counts <- table(energy_clean$ProductionTypeName)

library(forcats)

# only include unique production resource names
unique_sites <- energy_clean[!duplicated(energy_clean$PowerSystemResourceName), ]

unique_sites %>%
  group_by(ProductionTypeName) %>%
  summarize(countN = n()) %>%
  arrange(countN) %>%  # First sort the dataframe but NOT the factor levels
  mutate(ProductionTypeName = fct_reorder(ProductionTypeName, countN)) %>% # This trick updates the factor levels
    ggplot(aes(ProductionTypeName, countN, fill = countN)) + 
    geom_bar(stat = "identity") + 
    coord_flip() +
    scale_fill_continuous(high = "#132B43", low = "#56B1F7") +
    geom_hline(yintercept = nrow(unique_sites)/nlevels(unique_sites$ProductionTypeName), color="blue") +
    labs(title = "No. of Production Plants per Energy Production Type 2020", fill = "Number of\nproduction plants") +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
# fossil gas has most production plants by far


# Low output on sundays ----
# aggregation by day
prod_by_day <- aggregate(energy_clean$ActualGenerationOutput, by = list(Day = energy_clean$Day), FUN = sum, na.rm = T)

prod_by_day$x <- prod_by_day$x * 0.001 # in gigawatt
plot(prod_by_day$Day, prod_by_day$x)
# question: why is production on day 9 (sunday) so low?

cap_by_day <- aggregate(energy$InstalledGenCapacity, by = list(Day = energy$Day), FUN = sum, na.rm = T)
cap_by_day$x <- cap_by_day$x * 0.001 # gigawatt
plot(cap_by_day$Day, cap_by_day$x)
# lower capacity on sundays 

energy_clean %>%
  filter(!is.na(ActualGenerationOutput)) %>%
  ggplot(aes(InstalledGenCapacity, ActualGenerationOutput, color = ActualGenerationOutput)) +
  geom_point() +
  facet_grid(~DayofWeek) +
  scale_fill_continuous(high = "#132B43", low = "#56B1F7")
# less capacity exceeding & less production sites with high capacity or high output on sundays


# Output exceeding capacity ----


# # line  chart ----
# # doesn't make much sense here as short time period
# energy_clean$Date <- as.Date(energy_clean$DateTime)
# 
# ggplot(energy_clean, aes(DateTime, ActualGenerationOutput, color = exceed)) + 
#   geom_line()
# ggplot(energy_clean, aes(DateTime, ActualGenerationOutput, color = ProductionGroup)) +
#   geom_line()
# # a lot of change over the course of a day

```


```{r merge with country boundaries}
library(rgdal)
energy <- energy_clean

aggreg <- aggregate(energy[c("ActualGenerationOutput", "ActualConsumption", "InstalledGenCapacity")], by = list(CountryCode = energy$CountryCode), FUN = sum, na.rm = T)
aggreg[,2:ncol(aggreg)] <- aggreg[,2:ncol(aggreg)] * 0.001

# eliminate differences
countries <- readOGR("data/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp", encoding="UTF-8")
countries$WB_A2
unique(energy$CountryCode) %in% countries$WB_A2

countries$CountryCode <- countries$WB_A2
unique(energy$CountryCode)[!unique(energy$CountryCode) %in% countries$WB_A2]

energy$CountryCode[energy$CountryCode == "NIE"] <- "GB"
unique(energy$CountryCode)[!unique(energy$CountryCode) %in% countries$WB_A2]

write.csv(energy, "data/day2_data_energy_prod_EU_2020-08-03_2020-08-09_aggregated.csv", encoding="UTF-8")

countries$CountryCode[countries$CountryCode == "NO"]
countries$CountryCode[countries$NAME_LONG == "Norway"] <- "NO"
unique(energy$CountryCode)[!unique(energy$CountryCode) %in% countries$CountryCode]

writeOGR(countries, layer = "ne_10m_admin_0_countries_ctry_code", "data/ne_10m_admin_0_countries/ne_10m_admin_0_countries_ctry_code.shp", driver = "ESRI Shapefile", encoding="UTF-8")

# join 
library(tigris)
merged <- geo_join(countries, energy, "CountryCode", "CountryCode", how = "inner")

writeOGR(join, layer = "merged", "merged_countries_ctry_code.shp", driver = "ESRI Shapefile", encoding="UTF-8")

```


```{r patchwork package}
# ggplot doesn't allow you to easily integrate multiple plots
# the 'patchwork' package makes it ridiculously simple to combine separate ggplots into the same graphic
# e.g. by providing mathematical operators for combining multiple plots
# mainly used for ggplot

# install.packages("patchwork")
library(ggplot2)
library(patchwork)

# Basic use ----
e1 + e2

# last added plot is the active one, and will receive any addition of new ggplot2 objects
e1 + e2 + labs(subtitle = 'This will appear in the last plot')

# adding patchworks to create nested patchwork
patch <- e1 + e2
e3 + patch


# Controlling Layout ----
# By default, patchwork will try to keep the grid square, and fill it out in row order
e1 + e2 + e3 + e4

e1 + e2 + e3 + e4 + plot_layout(nrow = 4, byrow = FALSE)


# Stacking and packing plots ----
# direct way of placing plots below or next to each other
# | will place the plots beside each other, while / will stack them:
e1 | e2 | e3 | e4
e1 / e2

# operators can be nested to receive more complex layouts
e1 | (e2 / e3)

# nesting three plots on top of a third
(e1 | e2 | e3) /
      e4

# Annotating the composition ----
# annotate the whole composition
(e1 | (e2 / e3)) + 
  plot_annotation(title = 'Energy Production 2020')

# enumerate plots to identify subplots
# 'A' for upper case letters, ‘1’ for numbers, ‘a’ for lowercase letters, ‘I’ for uppercase Roman numerals, and ‘i’ for lowercase Roman numerals
e1 + e2 + e3 + 
  plot_annotation(tag_levels = 'A')

# adjust the font size of the tags with ggplot theme
e1 + e2 + e3 + 
  plot_annotation(tag_levels = 'A') & 
    theme(plot.tag = element_text(size = 8))

# Placing Legends in a Common Place
e1 + e2 + plot_layout(guides="collect")


# Adding non-ggplot data ----
# but standard alignment you'd get when adding ggplots doesn't work. There is no way to get consistent alignment between ggplots and base graphics, need par() for this
library(gridGraphics)
e1 + ~plot(mtcars$mpg, mtcars$disp, main = 'Plot 2')

```

