---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart A

```{r scatter plot, echo=FALSE}
data()
# Diameter, Height and Volume for Black Cherry Trees
data(trees)
attach(trees)

plot(Height, Volume) +
abline(lm(Volume~Height), col = "red") 

```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart B

```{r}
# Basic Scatterplot Matrix
pairs(~Height+Volume+Girth,data=trees,
   main="Simple Scatterplot Matrix")

```

### Chart C

```{r stats, eval=FALSE}
attach(trees)

summary(Girth)
hist(Girth)

```


```{r group scatter plot, echo=FALSE}
# grouped by third variable
trees$group_var <- 3

trees$group_var[Girth <= 11.05] <- 1
trees$group_var[Girth >= 15.25] <- 2

# color plot according to group
trees$group_col[trees$group_var == 1] <- "blue"
trees$group_col[trees$group_var == 2] <- "purple"
trees$group_col[trees$group_var == 3] <- "pink"

plot(Height, Volume, col = trees$group_col)
# Add legend to scatterplot
legend("topleft",                                 
       legend = c("Girth <= 11.05", "Girth >= 11.05", "Girth >= 15.25"),
       col = c("blue", "purple", "pink"),
       pch = c(1,1,1))

```

